config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  
  resources :quotes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates_presence_of :first, :last, :email, :phone
  VALID_NAME_REGEX = /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/
  validates :first, length: { minimum: 1, maximum: 25 }, format: { with: VALID_NAME_REGEX }
  validates :last, length: { minimum: 1, maximum: 25 }, format: { with: VALID_NAME_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  VALID_PHONE_REGEX = /\A\d{10}\z/
  validates :phone, length: { minimum: 10, maximum: 10 }, format: { with: VALID_PHONE_REGEX }
  before_save :downcase_email

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def show
    @quote = Quote.find(params[:id])
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      flash[:info] = 'Your quote has been submitted.  Someone will reach out to you shortly.'
      redirect_to quotes_path
    else
      render 'new'
    end
  end

  private
    def quote_params
      params.require(:quote).permit(:first, :last, :email, :phone)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    Some shop for selling stuff...
  </small>
  <nav>
    <ul>
      <li><%= link_to 'Facebook', '#' %></li>
      <li><%= link_to 'Twitter', '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to "lllr", root_path, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>

        <li><%= link_to 'Get a Quote', new_quote_path %></li>
        <li><%= link_to 'Quotes', quotes_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/quotes/index.html.erb
<% provide(:title, 'Quotes') %>
<h1>Quotes</h1>
<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= link_to "#{quote.first} #{quote.last}", quote %></td>
        <td><%= quote.email %></td>
        <td><%= quote.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/quotes/new.html.erb
<% provide(:title, 'New Quote') %>
<h1>New Quote</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@quote) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :first_name %>
      <%= f.text_field :first, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.submit 'Submit', class: 'btn btn-primary'  %>
    <% end %>
  </div>
</div>

app/views/quotes/show.html.erb
<% provide(:title, "Individual Quote") %>
<h1>Individual Quote</h1>
<p><%= "#{@quote.first} #{@quote.last}" %></p>
<p><%= @quote.email %></p>
<p><%= @quote.phone %></p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'LLLR') %>
<h1>Home</h1>